#!/usr/bin/env python
# -*- coding: utf-8 -*-
import gval.script
import sys

if __name__ == '__main__':
    script = gval.script.Script()
    method, args = script.avaliar(sys.argv[0], "consultar",
            "--jogo", sys.argv[1], "--concurso", sys.argv[2])

    method(*args)
